apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hostsubnets.egressha.com
spec:
  conversion:
    strategy: None
  group: egressha.com
  names:
    kind: Hostsubnet
    listKind: HostsubnetList
    plural: hostsubnets
    shortNames:
    - hs
    singular: hostsubnet
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.host_name
      name: Host
      type: string
    - jsonPath: .spec.host_ip
      name: Host IP
      type: string
    - jsonPath: .spec.egress_cidrs
      name: Egress CIDRS
      type: string
    - jsonPath: .spec.egress_ips
      name: Egress IP
      type: string
    - jsonPath: .spec.status
      name: Status
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              egress_cidrs:
                items:
                  pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|21|22|24|26|32)$)
                  type: string
                type: array
              egress_ips:
                items:
                  pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}
                  type: string
                type: array
              host_ip:
                pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}
                type: string
              host_name:
                type: string
              status:
                pattern: (true|false)
                type: string
            type: object
        type: object
    served: true
    storage: true
